## Imprimir Elementos do Array

**Problema**: Considere este array 1X1:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Imprima o 3º e o 9º elemento do array.
2. Altere o 3º e o 9º elemento para 100.


In [3]:
# escreva o código aqui
import numpy as np
arr_1d = np.array([53, 78, 90, 12, 15, 65, 44, 32, 29, 36])

#Imprimir o 3° e o 9° elemento do array
print("90", arr_1d[2])
print("29", arr_1d[8])

#Aletar o 3° e o 9° elemento para 100 
arr_1d[2] = 100
arr_1d[8] = 100

print("Array após a alteração:", arr_1d)

90 90
29 29
Array após a alteração: [ 53  78 100  12  15  65  44  32 100  36]


## Atualize os Elementos Diagonais do Array Multidimensional

**Problema**: Considerando este array 3x3, altere todos os elementos diagonais da matriz para 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```





In [4]:
#Escreva o código aqui
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#Atualizar todos os elementos diagonais para 0
np.fill_diagonal(arr_2d, 0)

print("Matriz após atualização dos elemntos diagonais:\n", arr_2d)

Matriz após atualização dos elemntos diagonais:
 [[0 2 3]
 [4 0 6]
 [7 8 0]]


## Números de Linhas e Colunas

**Problema**: Escreva um programa para encontrar o número de linhas e colunas presentes na matriz abaixo. 
Observação: Inicialize a matriz usando NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```



In [5]:
# escreva o código aqui
import numpy as np

A = np.array([[9,5,6,1,-2],
              [3,-8,1,2,0],
              [6,9,3,3,5]])

num_linhas, num_colunas = A.shape

print(f"Número de linhas: {num_linhas}")
print(f"Número de colunas: {num_colunas}")

Número de linhas: 3
Número de colunas: 5


## Multiplicação Escalar

**Problema**: Imprima cada elemento da matriz a seguir. Inicialize a matriz usando NumPy.  <br />
Além disso, multiplique a matriz por n = 150 e imprima a matriz após a multiplicação.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```


   

In [9]:
import numpy as np

B = np.array([[-8,0,2,4],
              [5,2,-1,7]])

#Imprimir cada elemento da matriz B
print("Matriz B antes da multiplicação:")
print(B)

#Multiplicar a matriz por n = 150
n= 150
B *= n

print(f"\nMatriz B após a multiplicação por {n}:\n", B)

Matriz B antes da multiplicação:
[[-8  0  2  4]
 [ 5  2 -1  7]]

Matriz B após a multiplicação por 150:
 [[-1200     0   300   600]
 [  750   300  -150  1050]]
