O **Tiro com Arco** é um jogo em que os jogadores atiram flechas de ponta afiada em um alvo redondo com 10 anéis.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg"> 

## Problema de Aprendizado por Reforço (RL) a Resolver
Acerte o centro do alvo que proporciona a recompensa máxima

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Número de **Estados**: ?

Número de **Ações**: ?




In [2]:
#importe as bibliotecas
import numpy as np

# Numero de estados e ações
num_estados = 5
num_acoes = 3

## Matriz de Recompensas
A Matriz de Recompensas representa os estados como linhas e as ações como colunas com os respectivos valores de recompensas atribuídos a um determinado par de estado e ação.

In [3]:
#Defina a matriz de recompensas
reward_matrix = np.array([[0, -10, -10],  # Estado 0
    [-10, 10, -10],  # Estado 1
    [-10, -10, 10],  # Estado 2
    [-10, 10, -10],  # Estado 3
    [-10, -10, 0]    # Estado 4
    ])

# Matriz Q iniclamente todos os elementos zerados
Q_matrix = np.zeros((num_estados, num_acoes))

## Execute Ações Aleatoriamente

In [4]:
#Defina shoot()
def shoot():
    return np.random.randint(num_acoes)

#Executar a ação
def take_action(state, reward_matrix):
    action = shoot()
    reward = reward_matrix[state, action]
    print(f"Ação escolhida: {action}, Recompensa: {reward}")

    #Testando a função take action
    estado_atual = 2
    acao, recompensa = take_action(estado_atual, reward_matrix)

##Matriz Q
O **Aprendizado Q** é um algoritmo de aprendizado por reforço. Dado o estado atual, ele ajuda a encontrar a melhor ação a ser tomada pelo agente.

A **Matriz Q** representa a recompensa recebida após uma ação específica no estado atual. Inicialmente, todos os elementos da matriz Q estão zerados.


In [5]:
#Crie a matriz Q
print("\nMatriz Q inicial:")
print(Q_matrix)



Matriz Q inicial:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##Execute uma Ação

In [10]:
#Defina take_action

def take_action(reward_matrix):
  
     #Chame a função shoot() para obter a ação
     action = shoot()
     #Imprima a ação
     print(f"Ação escolhida: {action}")
     #Obtenha a recompensa correspondente usando a matriz de recompensas
     reward = reward_matrix[num_estados, action]
     #Imprima a recompensa
     print(f"Recompensa obtida: {reward}")

     return action, reward

#Teste a função take_action
estado_atual = 2
#acao, recompensa = take_action(estado_atual, reward_matrix)
